package me.MiniDigger.RideThaMob.v1_10_R1.entities;

import me.MiniDigger.RideThaMob.api.RideThaMob;
import me.MiniDigger.RideThaMob.v1_10_R1.util.NMSHandler_1_10_R1;
import net.minecraft.server.v1_10_R1.Entity;
import net.minecraft.server.v1_10_R1.EntityHuman;
import net.minecraft.server.v1_10_R1.EntityLiving;
import net.minecraft.server.v1_10_R1.EntityCreeper;
import net.minecraft.server.v1_10_R1.World;

/**
 * This class may be generated by a bot. Gen date: 12.06.16 18:51
 */
public class RideAbleCreeper extends EntityCreeper {

    private double rideSpeed;
    private boolean fly;// TODO Implement Flying
    private double jumpHeight;// TODO Implement Jumping
    private double sidewaysMod;
    private double backwardsMod;
    private double stepHeight;
    private int updateVal = 0;
    private RideThaMob plugin;

    public RideAbleCreeper( final World world ) {
        super( world );

        plugin = NMSHandler_1_10_R1.getInstance().getPlugin();

        updateStuff();
    }

    private void updateStuff() {
        rideSpeed = plugin.getConfigHandler().getRideSpeed( getBukkitEntity().getType() );
        fly = plugin.getConfigHandler().getFly( getBukkitEntity().getType() );
        jumpHeight = plugin.getConfigHandler().getJumpHeight( getBukkitEntity().getType() );
        sidewaysMod = plugin.getConfigHandler().getSidewaysMod( getBukkitEntity().getType() );
        backwardsMod = plugin.getConfigHandler().getBackwardsMod( getBukkitEntity().getType() );
        stepHeight = plugin.getConfigHandler().getStepHeight( getBukkitEntity().getType() );
    }

    @Override
    public void g( float f, float f1 ) {
        // stearing passenger
        // NMS: bw -> getPassenger
        EntityLiving entityliving = (EntityLiving) bw();
        if ( entityliving == null ) {
            // search first human passenger
            for ( final Entity e : passengers ) {
                if ( e instanceof EntityHuman ) {
                    entityliving = (EntityLiving) e;
                    break;
                }
            }
            if ( entityliving == null ) {
                super.g( f, f1 );
                return;
            }
        }

        if ( plugin.getUpdateVal() > updateVal ) {
            updateVal = plugin.getUpdateVal();
            updateStuff();
        }

        // set yaw pitch
        this.lastYaw = this.yaw = entityliving.yaw;
        this.pitch = entityliving.pitch * 0.5F;
        this.setYawPitch(this.yaw, this.pitch);
        // NMS aQ, a0
        this.aQ = this.aO = this.yaw;

        // NMS: set sideMod
        f = (float) (entityliving.bf * sidewaysMod);

        // NMS: set backMod
        f1 = entityliving.bg;
        if ( f1 <= 0.0f ) {
            f1 *= backwardsMod;// backwards slower
        }

        // set speed an go!
        this.l( (float) rideSpeed );
        super.g( f, f1 );

        //NMS: P -> stepHeight
        P = (float) stepHeight;
    }
}
